name: servel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  country_pickers: ^3.0.1
  flutter_localizations: 
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.0
  flutter_screenutil: ^5.8.4
  tcard: ^1.3.5
  http: ^1.4.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
